project:
  type: book
  output-dir: docs
book:
  title: "ROS 2 : Mea Via et Mea Disciplina "
  author: "Rishikesavan Ramesh, Manoj Murali"
  date: "4/5/2023"
  chapters:
    - index.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
  pdf:
    documentclass: scrreprt



